services:
  vp_server_service:
    build:
      dockerfile: ./Dockerfile
    container_name: vp_server
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "${SV_PORT}:${INTERN_SV_PORT}"

networks:
  vp_net:
    driver: bridge
